##### Simulation code for relative effects transportability
# codes for obtaining the balancing intercepts are borrowed from https://github.com/pzivich/publications-code/blob/master/ReBalancingIntercept/balance_intercept.R 

###########------- Libraries
library("mvtnorm")
library("tidyverse")
library("rootSolve")
library("Hmisc")
library("SciViews")
library("gam")
library("nnet")
library("boot")
library("dummy")
library("latex2exp")

###########------- Scenario 1
# S=1 (trial), A=0, 1, P(A=1|X, S=1)=0.5
# S=0 (observational), A=0, P(A=1|X, S=0)=0 no treatment variation in the observational
# n_1=500/1000/5000, n_0=5000/6000/10000, p (dimension of X)=5, each X is independently uniform distributed

###########------- Data generation 
Gen=function(n, n_1, p){
  # parameter specification
  beta_coefs=matrix(rep(ln(1.05),p),byrow=F,nrow=1)      # coef of S model
  ## X~U(0, 1)
  X=matrix(NA,nrow=n,ncol=p); for (i in 1:p) {X[,i]=runif(n,0,1)}
  ## S
  tosolve <- function(ints, fxname, goalmarg){
    values <- fxname(ints)                          # simulated individual expected values at given intercept value
    if(is.null(dim(values))){                       # obtain mean of simulated individual expected values
      empmeans <-  mean(values)}else{
        empmeans <-  colMeans(values)
      }     
    diff = empmeans - goalmarg                      # difference from empirical mean to goal marginal distribution
    return(diff)                              
  }
  gen_pr_s <- function(beta0){
    prob_s <- plogis(as.numeric(beta0 + beta_coefs%*%t(X) ))  # probability generated by model at given intercept value
    return(prob_s)
  }
  goalmarg_s <- n_1/n
  roots <- multiroot(f=tosolve, start=c(-1), fxname=gen_pr_s, goalmarg=goalmarg_s, atol=1e-12)$root # find root for R model
  S=rbinom(n, size=1, p=gen_pr_s(roots))                     # simulate S using intercept solution
  ## A
  A=c(); A[S==1]=rbinom(length(which(S==1)),1,p=0.5); A[S==0]=0
  ## Y
  ### Functions for generating Y
  m=function(X) -0.5-0.4*X[,1]-0.4*X[,2]-0.4*X[,3]-0.4*X[,4]-0.4*X[,5]
  g=function(X)      0.4*X[,1]+0.5*X[,2]-0.5*X[,3]-0.6*X[,4]+0.6*X[,5]
  r=function(X)      0.5*X[,1]-0.1*X[,2]+0.3*X[,3]+0.2*X[,4]-0.3*X[,5]
  
  Y0=Y1=Y=rep(1,n)
  Y0=rbinom(n,1,p= exp(m(X)+S*g(X)) )
  Y1=rbinom(n,1,p= exp(m(X)+r(X)+S*g(X)) )
  Y=A*Y1+(1-A)*Y0
  return(data.frame(X,S,A,Y,Y0,Y1))
}

# ###########------ True value of alpha: E(Y1|S=0), beta: E(Y0|S=0), theta: alpha/beta
GetTrue=function(n, n_1, p){
  mean_alpha=NULL;mean_beta=NULL;mean_theta=NULL
  for (i in 1:100000) {
    Data=Gen(n, n_1, p)
    Y_1=Data$Y1
    Y_0=Data$Y0
    mean_alpha_temp=mean(Y_1[which(Data$S==0)])
    mean_alpha=c(mean_alpha,mean_alpha_temp)
    mean_beta_temp=mean(Y_0[which(Data$S==0)])
    mean_beta=c(mean_beta,mean_beta_temp)
    mean_theta=mean_alpha/mean_beta
  }
  alpha=mean(mean_alpha);beta=mean(mean_beta);theta=mean(mean_theta)
  results=c(alpha,beta,theta)
  return(results)
}
true_5500_500=GetTrue(5500,500,5)
true_6000_1000=GetTrue(6000,1000,5)
true_10000_5000=GetTrue(10000,5000,5)


###########------ Function of covariate shits for misspecification
Mis_X=function(X){
  # X[,2]=sin(X[,2])^3
  X[,2]=X[,2]
  return(X)
}

###########------ Function of estimation and inference
EST=function(n, n_1, p){
  Data=Gen(n, n_1, p)
  A=Data$A; S=Data$S; Y=Data$Y; X=Data[,1:p]; MX=Mis_X(X); MData=data.frame(MX,S,A,Y)
  ################################ for alpha
  ###### nuisance
  # kappa
  kappa=(sum(1-S)/n)^(-1)
  #q=P(A=1|X,S=1)
  model_A=glm(A~X1+X2+X3+X4+X5, family="binomial", data=Data[S==1,])
  q=predict(model_A, newdata=Data, type="response")
  
  # tau=P(S=0|X)/{1-P(S=0|X)}
  model_S=glm((1-S)~X1+X2+X3+X4+X5, family="binomial", data=Data)
  P_S=predict(model_S, type="response")
  tau=P_S/(1-P_S)
  
  model_MS=glm((1-S)~-1+X2, family="binomial", data=MData)
  MP_S=predict(model_MS, newdata=MData,type="response")
  Mtau=MP_S/(1-MP_S)
  
  # outcomes
  # correct outcome models
  model_mu_00=glm(Y~X1+X2+X3+X4+X5, family = "binomial", data=Data[S==0 & A==0,])
  mu_00=predict(model_mu_00, newdata = Data,type="response")
  
  model_mu_01=glm(Y~X1+X2+X3+X4+X5, family = "binomial", data=Data[S==1 & A==0,])
  mu_01=predict(model_mu_01, newdata = Data,type="response")
  
  model_mu_11=glm(Y~X1+X2+X3+X4+X5, family = "binomial", data=Data[S==1 & A==1,])
  mu_11=predict(model_mu_11, newdata = Data,type="response")
  
  # misspecified outcome models
  Mmodel_mu_00=glm(Y~-1+X2, family = "binomial", data=Data[S==0 & A==0,])
  Mmu_00=predict(Mmodel_mu_00, newdata = Data,type="response")
  
  Mmodel_mu_01=glm(Y~-1+X2, family = "binomial", data=Data[S==1 & A==0,])
  Mmu_01=predict(Mmodel_mu_01, newdata = Data,type="response")
  
  Mmodel_mu_11=glm(Y~-1+X2, family = "binomial", data=Data[S==1 & A==1,])
  Mmu_11=predict(Mmodel_mu_11, newdata = Data,type="response")
  
  # outcome modeling, 4 nuisance, mu_11, mu_00, tau and Mmu_01 has to be correct, 
  # 01 v, 11 v, 00 v, tau v
  est_all_v=kappa*mean((1-S)*mu_11/Mmu_01*(Y)+S*tau*mu_00/Mmu_01*(A/q*(Y-mu_11)-(1-A)/(1-q)*mu_11/Mmu_01*(Y-Mmu_01)))
  conv_all_v=kappa*mean((1-S)*mu_11+S*tau*A/q*(Y-mu_11))
  # 01 v, 11 v, 00 x, tau x 
  est_11=kappa*mean((1-S)*mu_11/Mmu_01*(Y)+S*Mtau*Mmu_00/Mmu_01*(A/q*(Y-mu_11)-(1-A)/(1-q)*mu_11/Mmu_01*(Y-Mmu_01)))
  conv_11=kappa*mean((1-S)*mu_11+S*Mtau*A/q*(Y-mu_11))
  # 01 v, 11 x, 00 v, tau v
  est_00=kappa*mean((1-S)*Mmu_11/Mmu_01*(Y)+S*tau*mu_00/Mmu_01*(A/q*(Y-Mmu_11)-(1-A)/(1-q)*Mmu_11/Mmu_01*(Y-Mmu_01)))
  conv_00=kappa*mean((1-S)*Mmu_11+S*tau*A/q*(Y-Mmu_11))
  # 01 v, 11 x, 00 x, tau x
  est_all_x=kappa*mean((1-S)*Mmu_11/Mmu_01*(Y)+S*Mtau*Mmu_00/Mmu_01*(A/q*(Y-Mmu_11)-(1-A)/(1-q)*Mmu_11/Mmu_01*(Y-Mmu_01)))
  conv_all_x=kappa*mean((1-S)*Mmu_11+S*Mtau*A/q*(Y-Mmu_11))
  
  results=c(est_all_v,conv_all_v,
            est_11,conv_11,
            est_00,conv_00,
            est_all_x,conv_all_x)
  return(results)
  
}

k=5000

vec_5500_500=matrix(NA,nrow=k,ncol=8)
start_time <- Sys.time();for (i in 1:k) {set.seed(i+123);vec_5500_500[i,]=EST(5000, 500, 5)};end_time <- Sys.time();elapsed_time <- end_time - start_time;end_time;elapsed_time
bias_5500_500=colMeans(vec_5500_500)-true_5500_500[1]
sim_sd_5500_500=apply(vec_5500_500,2,sd)


vec_6000_1000=matrix(NA,nrow=k,ncol=8)
start_time <- Sys.time();for (i in 1:k) {set.seed(i+123);vec_6000_1000[i,]=EST(6000, 1000, 5)};end_time <- Sys.time();elapsed_time <- end_time - start_time;end_time;elapsed_time
bias_6000_1000=colMeans(vec_6000_1000)-true_6000_1000[1]
sim_sd_6000_1000=apply(vec_6000_1000,2,sd)


vec_10000_5000=matrix(NA,nrow=k,ncol=8)
start_time <- Sys.time();for (i in 1:k) {set.seed(i+123);vec_10000_5000[i,]=EST(10000, 5000, 5)};end_time <- Sys.time();elapsed_time <- end_time - start_time;end_time;elapsed_time
bias_10000_5000=colMeans(vec_10000_5000)-true_10000_5000[1]
sim_sd_10000_5000=apply(vec_10000_5000,2,sd)
############################### PLOT ALL
plot( c(1,4), las = 2, xlim =c(0.6, 4.4), ylim = c(-0.2, 0.2),  type="n",
      xlab=TeX(r'(Correct Model(s))',bold=TRUE), ylab=TeX(r'(Bias$\pm$SD)', bold=TRUE), 
      # main="Comparison of different model performance, n_1=500/1000/5000", 
      xaxt="n",
)
axis(1, at=1:4, labels=c(TeX(r'($\{\mu_{1, 1}(X), \mu_{0}(X), \tau(X)\}$)', bold=FALSE),TeX(r'($\{\mu_{1, 1}(X)\}$)', bold=FALSE),TeX(r'($\{\mu_{0}(X), \tau(X)\}$)', bold=FALSE),TeX(r'(None)', bold=FALSE)) )
#### 500
bias_all_v=bias_5500_500[1:2];bias_11=bias_5500_500[3:4];bias_00=bias_5500_500[5:6]
sd_all_v=sim_sd_5500_500[1:2];sd_11=sim_sd_5500_500[3:4];sd_00=sim_sd_5500_500[5:6]
for (i in 1:2){
  points(0.6+0.05*i,bias_all_v[i],pch=(i-1)*10, cex=1.5)
  segments(0.6+0.05*i, bias_all_v[i]-sd_all_v[i], 0.6+0.05*i, bias_all_v[i]+sd_all_v[i], lwd=3, lty = 3 )
}
for (i in 1:2){
  points(1.6+0.05*i,bias_11[i],pch=(i-1)*10, cex=1.5)
  segments(1.6+0.05*i, bias_11[i]-sd_11[i], 1.6+0.05*i, bias_11[i]+sd_11[i], lwd=3, lty = 3 )
}
for (i in 1:2){
  points(2.6+0.05*i,bias_00[i],pch=(i-1)*10, cex=1.5)
  segments(2.6+0.05*i, bias_00[i]-sd_00[i], 2.6+0.05*i, bias_00[i]+sd_00[i], lwd=3, lty = 3 )
}
for (i in 1:2){
  points(3.6+0.05*i,bias_all_x[i],pch=(i-1)*10, cex=1.5)
  segments(3.6+0.05*i, bias_all_x[i]-sd_all_x[i], 3.6+0.05*i, bias_all_x[i]+sd_all_x[i], lwd=3, lty = 3 )
}
#### 1000
bias_all_v=bias_6000_1000[1:2];bias_11=bias_6000_1000[3:4];bias_00=bias_6000_1000[5:6]
sd_all_v=sim_sd_6000_1000[1:2];sd_11=sim_sd_6000_1000[3:4];sd_00=sim_sd_6000_1000[5:6]
for (i in 1:2){
  points(0.8+0.05*i,bias_all_v[i],pch=(i-1)*10, cex=1.5)
  segments(0.8+0.05*i, bias_all_v[i]-sd_all_v[i], 0.8+0.05*i, bias_all_v[i]+sd_all_v[i], lwd=3, lty = 2 )
}
for (i in 1:2){
  points(1.8+0.05*i,bias_11[i],pch=(i-1)*10, cex=1.5)
  segments(1.8+0.05*i, bias_11[i]-sd_11[i], 1.8+0.05*i, bias_11[i]+sd_11[i], lwd=3, lty = 2 )
}
for (i in 1:2){
  points(2.8+0.05*i,bias_00[i],pch=(i-1)*10, cex=1.5)
  segments(2.8+0.05*i, bias_00[i]-sd_00[i], 2.8+0.05*i, bias_00[i]+sd_00[i], lwd=3, lty = 2 )
}
for (i in 1:2){
  points(3.8+0.05*i,bias_all_x[i],pch=(i-1)*10, cex=1.5)
  segments(3.8+0.05*i, bias_all_x[i]-sd_all_x[i], 3.8+0.05*i, bias_all_x[i]+sd_all_x[i], lwd=3, lty = 2 )
}
### 50000
bias_all_v=bias_10000_5000[1:2];bias_11=bias_10000_5000[3:4];bias_00=bias_10000_5000[5:6]
sd_all_v=sim_sd_10000_5000[1:2];sd_11=sim_sd_10000_5000[3:4];sd_00=sim_sd_10000_5000[5:6]
for (i in 1:2){
  points(0.99+0.05*i,bias_all_v[i],pch=(i-1)*10, cex=1.5)
  segments(0.99+0.05*i, bias_all_v[i]-sd_all_v[i], 0.99+0.05*i, bias_all_v[i]+sd_all_v[i], lwd=3, lty = 1 )
}
for (i in 1:2){
  points(1.99+0.05*i,bias_11[i],pch=(i-1)*10, cex=1.5)
  segments(1.99+0.05*i, bias_11[i]-sd_11[i], 1.99+0.05*i, bias_11[i]+sd_11[i], lwd=3, lty = 1 )
}
for (i in 1:2){
  points(2.99+0.05*i,bias_00[i],pch=(i-1)*10, cex=1.5)
  segments(2.99+0.05*i, bias_00[i]-sd_00[i], 2.99+0.05*i, bias_00[i]+sd_00[i], lwd=3,lty = 1 )
}
for (i in 1:2){
  points(3.99+0.05*i,bias_all_x[i],pch=(i-1)*10, cex=1.5)
  segments(3.99+0.05*i, bias_all_x[i]-sd_all_x[i], 3.99+0.05*i, bias_all_x[i]+sd_all_x[i], lwd=3, lty = 1 )
}
abline(h=0)

legend(0.5,-0.1, c(TeX(r'($\widehat{\alpha_{1}}$)', bold=FALSE),TeX(r'($\widehat{\alpha_{1}'}$)', bold=FALSE)),  horiz = F, bty = 'n', cex=1.4,pch=c(0,10,20))
legend(4.05, -0.1, c(TeX(r'($n_1=500$)', bold=FALSE),TeX(r'($n_1=1000$)', bold=FALSE),TeX(r'($n_1=5000$)', bold=FALSE)),  horiz = F, bty = 'n', cex=1.4,lty=c(3,2,1),lwd=3)




